---
-
  hosts: all
  tasks: 
    - 
      file: 
        path: /download
        state: directory
      name: "create directory"
-
  hosts: all
  tasks:
    -
      maven_artifact:
        artifact_id: demo
        dest: /download
        group_id: com.example
        version: 0.0.1
        password: 123456
        repository_url: "http://host.docker.internal:8110/repository/springdemo/"
        username: admin
-
  hosts: all
  vars:
    app_name: developer-latest
    
  tasks:
  - name: create service file
    template:
       src: path.j2
       dest: /etc/systemd/system/demo-latest.service

  - name: start service
    service:
       name: demo-latest.service
       state: restarted
